services:
  # ğŸ˜ æ•°æ®åº“æœåŠ¡
  postgres:
    image: postgres:18-alpine
    container_name: blog-postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - blog-network

  # ğŸš€ ç¼“å­˜æœåŠ¡
  redis:
    image: redis:alpine
    container_name: blog-redis
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    networks:
      - blog-network

  # âš¡ï¸ ä½ çš„ NestJS åç«¯
  blog-backend:
    image: gdouzwt/blog-backend:latest
    container_name: blog-backend
    ports:
      - "3721:3721"
    environment:
      - DB_HOST=postgres
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}     # å¯¹åº”ä¸Šé¢çš„ POSTGRES_DB
      - REDIS_HOST=redis
      - REDIS_PORT=${REDIS_PORT}
    depends_on:
      - postgres
      - redis
    networks:               # ğŸ”§ ä¿®å¤1: å¿…é¡»åŠ å…¥åŒä¸€ä¸ªç½‘ç»œï¼
      - blog-network

  # ğŸ¨ å‰ç«¯ Nginx (åå‘ä»£ç†)
  blog-frontend:
    image: gdouzwt/blog-frontend:latest
    container_name: blog-frontend
    ports:
      - "5173:80"
    depends_on:
      - blog-backend
    networks:
      - blog-network

# å®šä¹‰ç½‘ç»œ
networks:
  blog-network:
    driver: bridge

volumes:
  pgdata: